### ISSUE TITLE
Git REPL mode

### ISSUE THREAD

**Issue by giordano** [bcbi/GitCommand.jl#21]
Idea [suggested](https://discourse.julialang.org/t/ann-gitcommand-jl-use-command-line-git-in-your-julia-packages/32330/3) by @oschulz: have a Git REPL mode.  [`ReplMaker.jl`](https://github.com/MasonProtter/ReplMaker.jl) could probably come in handy to do this.

**Comment by DilumAluthge** [comment]
I think it’s a great idea, and ReplMaker looks like the right idea.
