### ISSUE TITLE
Git REPL mode: disable automatic loading

### ISSUE THREAD

**Issue by DilumAluthge** [bcbi/GitCommand.jl#27]
By defualt, when you do either `import GitCommand` or `using GitCommand`, it automatically loads in the Git REPL mode. Perhaps some users will not want this? So we should have a way of disabling the automatic loading. Probably with an environment variable

**Comment by DilumAluthge** [comment]
Actually, the more that I think about it, we really shouldn't load it in automatically. If you want to use the Git REPL mode, it's quite easy to just run `GitCommand.git_repl()`. And then the REPL mode is available. I think it's better to be opt-in rather than opt-out.

**Comment by rapus95** [comment]
What's the code I need in startup file to have it enabled by default? I always get World age errors when I try calling `GitCommand.gitrepl()` in the startup.jl :/

**Comment by DilumAluthge** [comment]
> What's the code I need in startup file to have it enabled by default? I always get World age errors when I try calling `GitCommand.gitrepl()` in the startup.jl :/

That is a good question. Can you open a new issue as a feature request?
