### ISSUE TITLE
Capturing output

### ISSUE THREAD

**Issue by mkarikom** [bcbi/GitCommand.jl#36]
Here I just need to get the commit hash of the current branch.  
Here is the MWE:

git() do git
   check=run(\`$git rev-parse HEAD\`)
end

The full output, in my case is:
3d81668e8b4c05c0156ccebb5b5dcb5c4d4abf25
Process(\`~/.julia/artifacts/e23cd71823ebb56caf20e30921afd055f04d02a2/bin/git rev-parse HEAD\`, ProcessExited(0))

Then I look at what is stored:
julia> check
Process(\`git rev-parse HEAD\`, ProcessExited(0))

What I was expecting was:
julia> check
3d81668e8b4c05c0156ccebb5b5dcb5c4d4abf25

Where 3d8166... is the hash I need.
How do I just store the hash in `check`?

**Comment by DilumAluthge** [comment]
Replace this:
```
check=run(`$git rev-parse HEAD`)
```

With this:
```
check=read(`$git rev-parse HEAD`, String)::String
```

**Comment by mkarikom** [comment]
Thanks!
Is it possible to use that hash later?  Suppose I would like to git archive that specific hash, after a series of jobs:
MWE:
check=read(`$git rev-parse HEAD`, String)::String
... do some stuff, possibly involving a commit, ...
run(\`$git archive --format=tar --output=~/Desktop/test.tar $check\`)

output
fatal: Not a valid object name
ERROR: failed process: Process(`git archive --format=tar --output=/home/au/Desktop/test.tar '3d81668e8b4c05c0156ccebb5b5dcb5c4d4abf25
'\`, ProcessExited(128)) [128]

**Comment by giordano** [comment]
Probably need to trim the whitespace at the end?  Try
```julia
check = strip(read(`$git rev-parse HEAD`, String))
``

**Comment by mkarikom** [comment]
Works perfectly.  Really appreciate the instant solutions!
