### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by DilumAluthge** [bcbi/GitCommand.jl#4]

**Comment by DilumAluthge** [comment]
Our current public interface is that we have the `git()` function and the `@git_cmd` macro. I think those are working well.

We can add a REPL interface without breaking. We can also make bug fixes etc without breaking.

So i think we have a stable public interface now. I think we can release 1.0.

I’ll leave this issue open for a little while before I release 1.0.

@giordano Any objection to making a 1.0 with the current public API?

**Comment by giordano** [comment]
No objections, apart from the fact that fixing #15 could be a breaking change maybe?

**Comment by DilumAluthge** [comment]
> No objections, apart from the fact that fixing #15 could be a breaking change maybe?

Oh that’s a good point.

**Comment by DilumAluthge** [comment]
Here’s one idea:
- Stop exporting `@git_cmd`. This will need to be a breaking release, `0.2.0`.
- Release `1.0.0`.
- Fix the interpolation issue - no rush on this. Personally I have no idea how to fix it.
- Start exporting `@git_cmd` again. This doesn’t need to be a breaking release.

**Comment by giordano** [comment]
Sounds good
