### ISSUE TITLE
Idea: define macro git_cmd

### ISSUE THREAD

**Issue by fredrikekre** [bcbi/GitCommand.jl#6]
You could define `macro git_cmd` to support this syntax:

```
git`clone https://github.com/bcbi/GitCommand.jl`
```
which rewrites to a `run` call with the correct git binary. Or maybe it should just define a new `Cmd` that you run yourself (``run(git`clone ...`)`` might be nicer actually).

**Comment by DilumAluthge** [comment]
> which rewrites to a run call with the correct git binary

Personally I kind of like this approach better. That's how the `@pkg_str` macro works, right? If you do `pkg"my command"`, it will immediately run the command.

**Comment by fredrikekre** [comment]
Yea, its just that it doesn't look like a call so not as easily understood as the ``run(git`...`)`` example.

**Comment by fredrikekre** [comment]
And you might want to do something with the generated command, which you can't if it directly does the call, e.g.
```
cmd = git`....`

if something
   cmd = `$cmd $args`
end
```
or w/e.

**Comment by DilumAluthge** [comment]
Or:
```
a = read(git`blah blah blah`, String)
```

```
b = success(git`blah blah blah`)
```

**Comment by DilumAluthge** [comment]
So this is implemented in master now:
```julia
using GitCommand

run(git`clone https://github.com/JuliaRegistries/General`)
```

But note that interpolation does not work correctly. For example, this will not work:
```julia
using GitCommand

my_url = "https://github.com/JuliaRegistries/General"
run(git`clone $my_url`)
```

So if you need to interpolate, you need to use the original syntax:

```julia
using GitCommand

my_url = "https://github.com/JuliaRegistries/General"
git() do git
    run(`$git clone $my_url`)
end
```

**Comment by fredrikekre** [comment]
> note that interpolation does not work correctly

Seems like a bug then.
